### ISSUE TITLE
Don't support Apng like this APNG

### ISSUE THREAD

**Issue by jiechic** [aellerton/japng#2]
http://i4.tietuku.com/462f043ee14a698e.png

**Comment by aellerton** [comment]
Thanks for the report.

My main computer is offline at the moment. The chunks in the file look
reasonable. What happens when you try to load it?

**Comment by jiechic** [comment]
this apng is use gif2apng to optimize，then error message like this：

> 01-28 13:09:21.082 11876-11876/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: net.ellerton.japng.android.demo, PID: 11876
>                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ellerton.japng.android.demo/net.ellerton.japng.android.demo.PngViewActivity}: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                        at android.os.Looper.loop(Looper.java:135)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at java.lang.reflect.Method.invoke(Method.java:372)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>                                                     Caused by: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
>                                                        at net.ellerton.japng.argb8888.Argb8888Processors$IndexedColour8.processScanline(Argb8888Processors.java:168)
>                                                        at net.ellerton.japng.PngScanlineBuffer.decompress(PngScanlineBuffer.java:112)
>                                                        at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:151)
>                                                        at net.ellerton.japng.reader.DefaultPngChunkReader.readImageDataChunk(DefaultPngChunkReader.java:175)
>                                                        at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:66)
>                                                        at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
>                                                        at net.ellerton.japng.android.api.PngAndroid.readDrawable(PngAndroid.java:29)
>                                                        at net.ellerton.japng.android.demo.PngViewActivity.getComposedAnimation(PngViewActivity.java:169)
>                                                        at net.ellerton.japng.android.demo.view.ViewTabsFragment.onViewCreated(ViewTabsFragment.java:135)
>                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
>                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
>                                                        at android.app.BackStackRecord.run(BackStackRecord.java:834)
>                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
>                                                        at android.app.Activity.performStart(Activity.java:6005)
>                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
>                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
>                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                        at android.os.Looper.loop(Looper.java:135) 
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5254) 
>                                                        at java.lang.reflect.Method.invoke(Native Method) 
>                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

the optimize application is on http://gif2apng.sourceforge.net/

then 

I use mac sofeware previce open gif too save to apng，that's not think error，
I use apngopt to optimize the picture，then has some error info。

>  aellerton commented 2 days ago
> Thanks for the report.
> My main computer is offline at the moment. The chunks in the file look
> reasonable. What happens when you try to load it?

**Comment by lumien231** [comment]
Another example for an apng not working would be the clock from this page: http://littlesvr.ca/apng/samples.html

It crashes while loading:

> java.lang.NullPointerException
> at net.ellerton.japng.argb8888.Argb8888Processors$IndexedColour8.processScanline(Argb8888Processors.java:168)
> at net.ellerton.japng.PngScanlineBuffer.decompress(PngScanlineBuffer.java:112)
> at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:151)
> at net.ellerton.japng.reader.DefaultPngChunkReader.readImageDataChunk(DefaultPngChunkReader.java:175)
> at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:66)
> at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
> at net.ellerton.japng.Png.readArgb8888BitmapSequence(Png.java:49)
> at lumien.custommainmenu.lib.textures.TextureApng.load(TextureApng.java:84) @

**Comment by aellerton** [comment]
Thanks for this report. I will get to it soon...

**Comment by aellerton** [comment]
@jiechic please try with the latest master. Let me know how it goes and I'll update further.

**Comment by jiechic** [comment]
@aellerton now is the same bug with @lumien231

**Comment by bluesoho16** [comment]
@aellerton : Looks like that this is not fixed. Any update?
Here is a sample APNG that gives me the same error as @lumien231 
https://s3-us-west-2.amazonaws.com/scalre/temp/aerostar_small.png

**Comment by aellerton** [comment]
Hey there,
I haven't been able to look at the issues unfortunately. I don't know when
I will be able to, due to other commitments. Have you tried debugging? I'm
open to PRs...

**Comment by bluesoho16** [comment]
@aellerton : It turned out that the palette never get cloned when Argb8888ScanlineProcessor is cloned. I have to call setPalette() after the clone() call. So in Argb8888ScanlineProcessor.java, I made the following changes:

    /**
     * When processing a sequence of frames a caller may want to write to a completely
     * new bitmap for every frame or re-use the bytes in an existing bitmap.
     *
     * @param header of image to use as basis for calculating image size.
     *
     * @return processor that will write to a new bitmap.
     */
    public Argb8888ScanlineProcessor cloneWithNewBitmap(PngHeader header) {
        Argb8888ScanlineProcessor cloned = clone(header.bytesPerRow, new Argb8888Bitmap(header.width, header.height));
        if(this.palette != null){
        	cloned.setPalette(new Argb8888Palette(palette.argbArray));
        }
        return cloned;
    }

    /**
     * When processing a sequence of frames a caller may want to write to a completely
     * new bitmap for every frame or re-use the bytes in an existing bitmap.
     *
     * @param header of image to use as basis for calculating image size.
     *
     * @return processor that will write to the same bitmap as the current processor.
     */
    public Argb8888ScanlineProcessor cloneWithSharedBitmap(PngHeader header) {
        Argb8888ScanlineProcessor cloned = clone(header.bytesPerRow, bitmap.makeView(header.width, header.height));
        if(this.palette != null){
        	cloned.setPalette(new Argb8888Palette(palette.argbArray));
        }
        return cloned;
    }

**Comment by bluesoho16** [comment]
@aellerton : Another bug is in   BasicArgb8888Directorlava line #23:

I changed it from
        if (length <= 0 || length >= palette.size()) {
to
        if (length <= 0 || length > palette.size()) {

**Comment by aellerton** [comment]
Awesome, thanks! I'll integrate that...
